/**
 * Generates supabase/seed.sql from src/lib/seed-data.ts (the same data demo mode uses).
 * Usage: npm run seed:generate
 * All rows are flagged is_demo = true. Demo users are inserted into auth.users WITHOUT credentials, so nobody can sign in as them.
 */
import { writeFileSync } from "node:fs"
import { generateFavorites, generateRatings, SEED_APPS, SEED_DEVELOPERS, SEED_PARTNERS, SEED_USERS, uuid } from "../src/lib/seed-data"

const q = (s: string | null | undefined) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`)
const out: string[] = []
const push = (s = "") => out.push(s)

push("-- GENERATED by scripts/generate-seed.ts. DEMO DATA ONLY. Do not run in production.")
push("-- Demo domains use the reserved .example TLD, so the demo sites do not exist.")
push("begin;")
push()

push("-- users (no credentials; cannot sign in) -------------------------------")
for (const u of [...SEED_DEVELOPERS.map((d) => ({ id: d.id, username: d.username, name: d.displayName })), ...SEED_USERS.map((u) => ({ id: u.id, username: u.username, name: u.displayName }))]) {
  push(`insert into auth.users (id, instance_id, aud, role, email, raw_user_meta_data, created_at, updated_at) values (${q(u.id)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${q(`${u.username}@demo.pwanova.invalid`)}, ${q(JSON.stringify({ user_name: u.username, full_name: u.name, is_demo: true }))}::jsonb, now(), now()) on conflict (id) do nothing;`)
}
push()
push("-- profiles (created by trigger; enrich) ---------------------------------")
push(`update public.profiles set is_demo = true where id in (${[...SEED_USERS.map((u) => q(u.id)), ...SEED_DEVELOPERS.map((d) => q(d.id))].join(",")});`)
for (const u of SEED_USERS) push(`update public.profiles set username = ${q(u.username)}, display_name = ${q(u.displayName)} where id = ${q(u.id)};`)
for (const d of SEED_DEVELOPERS) push(`update public.profiles set username = ${q(d.username)}, display_name = ${q(d.displayName)}, bio = ${q(d.bio)}, website = ${q(d.website)}, is_verified = ${d.verified}, role = 'developer' where id = ${q(d.id)};`)
push()

push("-- partners --------------------------------------------------------------")
for (const p of SEED_PARTNERS) push(`insert into public.partners (id, name, slug, website, referral_code, status) values (${q(p.id)}, ${q(p.name)}, ${q(p.slug)}, ${q(p.website)}, ${q(p.referralCode)}, 'active') on conflict (id) do nothing;`)
push()

SEED_APPS.forEach((a, i) => {
  const id = uuid(4, i + 1)
  const dev = SEED_DEVELOPERS.find((d) => d.username === a.developer)!
  const partner = a.launch?.partner ? SEED_PARTNERS.find((p) => p.slug === a.launch!.partner) : undefined
  push(`-- ${a.name} ${"-".repeat(Math.max(2, 60 - a.name.length))}`)
  push(`insert into public.apps (id, developer_id, name, slug, tagline, description, url, domain, category, status, ownership_status, verification_status, is_pwa, is_installable, hosting_provider, build_tool, health_status, health_checked_at, is_featured, featured_at, is_demo, created_at) values (${q(id)}, ${q(dev.id)}, ${q(a.name)}, ${q(a.slug)}, ${q(a.tagline)}, ${q(a.description)}, ${q(`https://${a.slug}.example`)}, ${q(`${a.slug}.example`)}, ${q(a.category)}, 'published', ${a.verified ? "'verified_owner'" : "'claim_pending'"}, ${a.verified ? "'verified'" : "'unverified'"}, ${a.pwa}, ${a.installable}, ${q(a.host)}, ${q(a.build)}, 'online', now() - interval '3 hours', ${Boolean(a.featured)}, ${a.featured ? "now()" : "null"}, true, now() - interval '${a.daysOld} days') on conflict (id) do nothing;`)
  if (a.launch) push(`insert into public.app_sources (app_id, partner_id, source_name, source_url, source_type) values (${q(id)}, ${partner ? q(partner.id) : "null"}, ${q(a.launch.name)}, ${q(a.launch.url ?? partner?.website)}, ${q(a.launch.type)});`)
  push(`insert into public.app_checks (app_id, reachable, https_ok, responsive, mobile_optimized, manifest_ok, service_worker_ok, installable, offline_support, push_support, security_ok, status_code, response_ms, last_checked_at) values (${q(id)}, true, true, true, true, ${a.pwa}, ${a.serviceWorker}, ${a.installable}, ${a.offline}, ${a.push}, true, 200, ${180 + i * 37}, now() - interval '${20 + i * 9} minutes') on conflict (app_id) do nothing;`)

  const ratings = generateRatings(a, i)
  const rows = ratings.map((r) => `(${q(id)}, ${q(SEED_USERS[r.user].id)}, ${r.rating}, now() - interval '${r.daysAgo} days')`)
  for (let k = 0; k < rows.length; k += 100) push(`insert into public.ratings (app_id, user_id, rating, created_at) values ${rows.slice(k, k + 100).join(", ")} on conflict do nothing;`)

  a.reviews.forEach((r, k) => {
    const rid = uuid(5, i * 10 + k + 1)
    push(`insert into public.reviews (id, app_id, user_id, rating, title, body, helpful_count, is_demo, created_at) values (${q(rid)}, ${q(id)}, ${q(SEED_USERS[r.user].id)}, ${r.rating}, ${q(r.title)}, ${q(r.body)}, ${r.helpful}, true, now() - interval '${r.daysAgo} days') on conflict (id) do nothing;`)
    if (r.response) push(`insert into public.developer_responses (review_id, developer_id, body, created_at) values (${q(rid)}, ${q(dev.id)}, ${q(r.response)}, now() - interval '${Math.max(0, r.daysAgo - 1)} days') on conflict do nothing;`)
  })

  const favs = generateFavorites(a, i)
  if (favs.length) push(`insert into public.favorites (app_id, user_id, created_at) values ${favs.map((f) => `(${q(id)}, ${q(SEED_USERS[f.user].id)}, now() - interval '${f.daysAgo} days')`).join(", ")} on conflict do nothing;`)

  const sources = "array['pwanova_search','pwanova_search','homepage','homepage','product_hunt','partner','google','direct','direct','social','other']"
  const gen = (type: string, n: number) => push(`insert into public.app_events (app_id, event_type, source, created_at) select ${q(id)}, '${type}', (${sources})[1 + floor(random() * 11)::int], now() - (power(random(), 1.6) * interval '30 days') from generate_series(1, ${n});`)
  gen("view", Math.round(a.opens30d * 3.1))
  gen("open_app", a.opens30d)
  gen("install_click", Math.round(a.opens30d * 0.35))
  push()
})

push("commit;")
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n") + "\n")
console.log(`Wrote supabase/seed.sql (${out.length} lines)`)
